name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    name: Go Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18, 1.20, 1.22]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Fix Go module path for CI
        id: gomodfix
        run: |
          if [ -f go.mod ]; then
            MODPATH=$(grep '^module ' go.mod | awk '{print $2}')
            if [[ "$PWD" != *"$MODPATH" ]]; then
              echo "Moving sources to match module path for Go"
              mkdir -p /tmp/gopath/src/$MODPATH
              cp -r . /tmp/gopath/src/$MODPATH
              echo "workdir=/tmp/gopath/src/$MODPATH" >> $GITHUB_ENV
            else
              echo "workdir=$PWD" >> $GITHUB_ENV
            fi
          fi
      - name: Build
        run: make build
        working-directory: ${{ env.workdir }}
      - name: Test
        run: make test
        working-directory: ${{ env.workdir }}
      - name: Format
        run: make fmt
        working-directory: ${{ env.workdir }}
      - name: Upload Go binary
        uses: actions/upload-artifact@v4
        with:
          name: debugstory-binary
          path: bin/debugstory
        if: always()

  lua:
    name: Lua Lint & (Optional) Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: [v0.8.0, v0.9.0, stable]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1'
      - name: Set up Neovim ${{ matrix.neovim-version }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Install stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ github.token }}
      - name: Lint Lua
        run: |
          find lua plugin -name "*.lua" -print0 | xargs -0 stylua
      # Uncomment if you add busted tests
      # - name: Install busted
      #   run: luarocks install busted
      # - name: Run Lua tests
      #   run: busted 